fixLink = "/gorose/dist/"
languageCode = "zh-CN"
theme = "gorose"
suffixTitle = " - Gorose"
homeTitle = "Gorose ORM"
# SCANFILE: The local path begins with src(base on src directory). support external link.
scanFile = [
    ["Gorose GitHub", "https://github.com/gohouse/gorose"],
    ["中文文档", "src/zh-cn/index.md"],
    ["English document", "src/en/index.md"],
]
